# Generated by Django 4.2.18 on 2025-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images/'),
        ),
    ]
