# Generated by Django 4.2.18 on 2025-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='user_resume'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.IntegerField(editable=False),
        ),
    ]
