# Generated by Django 4.2.18 on 2025-01-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_profile_pfp_alter_profile_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='profile_images/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
