# Generated by Django 3.1.1 on 2025-02-17 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20250217_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='experience_level',
            field=models.CharField(choices=[('fresher', 'fresher'), ('1-3 years', '1-3 years'), ('4-6 years', '4-6 years'), ('7+ years', '7+ years')], default='fresher', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
