# Generated by Django 3.1.1 on 2025-02-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20250217_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
