# Generated by Django 3.1.1 on 2025-02-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20250217_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='salary',
        ),
    ]
