# Generated by Django 3.1.1 on 2025-02-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_post_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
