# Generated by Django 3.1.1 on 2025-02-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_post_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
