# Generated by Django 3.1.1 on 2025-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20250217_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
